import "./globals.css";

export const metadata = {
  title: {
    default: 'Free Online Teaching Platform | Klas',
    template: '%s | Klas'
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="./favicon.png" type="image/x-icon" />
      </head>
      <body>
          {children}
      </body>
    </html>
  );
}
